on:
  issue_comment:
    types: [created, deleted]
  workflow_dispatch:
jobs:
  blessing_from_the_knug:
    # This job only runs in 1/1000 chance
    runs-on: ubuntu-latest
    steps:
    - id: roll-dice
      run: echo "$(($RANDOM%1000))" >> $GITHUB_ENV
      shell: bash
      
    - id: debug
      run: echo "$GITHUB_ENV"

    - if: env.PROCEED != '0'
      name: Cancelling
      uses: andymckay/cancel-action@0.2

    - if: env.PROCEED != '0'
      name: Waiting for cancellation
      run: sleep 60
    
    - uses: GustafKisi/action_knugen@1.1
      with:
        message: "Wishing you fruitful outcomes in your efforts."
        token: ${{secrets.GITHUB_TOKEN}}
            
