on:
  issue_comment:
    types: [created, deleted]

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: GustafKisi/action_knugen@1.1
        with:
          message: "Knug."
          token: ${{secrets.GITHUB_TOKEN}}

  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: GustafKisi/action_knugen@1.1
        with:
          message: "Knug."
          token: ${{secrets.GITHUB_TOKEN}}
            
          
